import {
  img1,
  img2,
  img3,
  img4,
  img5,
  img6,
  img7,
  img8,
  img9,
  img10,
  img11,
  img12,
  img13,
  img14,
  img15,
  img16,
  img17,
  img18,
  img19,
  img20,
  img21,
  img22,
  img23,
  img24,
  img25,
  img26,
  img27,
  img30,
  img31,
  img32,
  img33,
  img34,
  img35,
  img36,
  img37,
  img38,
  img39,
  img40,
  img41,
  img42,
  img43,
  img44,
  img45,
  img46,
  img47,
  img48,
  img49,
  img50,
  img51,
  img52,
  img53,
  img54,
  img55,
  img56,
  img57,
  img58,
  img59,
  img60,
  img61,
  img62,
  img63,
  img64,
  img65,
  img66,
  img67,
  img68,
  img69,
  img70,
  img71,
  img72,
} from "./files.js";

export const scenes = [
  {
    title: "Haute Couture Nights — Paris",
    images: [img1, img2, img3, img4],
    gridItems: [
      { img: img1, caption: "Kai Vega" },
      { img: img2, caption: "Riven Juno" },
      { img: img3, caption: "Lex Orion" },
      { img: img4, caption: "Ash Kairos" },
      { img: img5, caption: "Juno Sol" },
      { img: img6, caption: "Soren Nyx" },
      { img: img7, caption: "Quinn Axon" },
      { img: img8, caption: "Zara Voss" },
      { img: img9, caption: "Hale B." },
      { img: img10, caption: "Gundra Wex" },
      { img: img11, caption: "Extra One" },
      { img: img12, caption: "Extra Two" },
    ],
  },
  {
    title: "Vogue Evolution — New York City",
    images: [img13, img14, img15, img16],
    gridItems: [
      { img: img13, caption: "Arlo Quinn" },
      { img: img14, caption: "Vera Kline" },
      { img: img15, caption: "Juno Vale" },
      { img: img16, caption: "Ember Dash" },
      { img: img17, caption: "Rylee Voss" },
      { img: img18, caption: "Harlow Nova" },
      { img: img19, caption: "Blake Lune" },
      { img: img22, caption: "Zephyr Kade" },
      { img: img21, caption: "Indigo Rae" },
      { img: img22, caption: "Kairo Jett" },
      { img: img23, caption: "Extra One" },
      { img: img24, caption: "Extra Two" },
    ],
  },
  {
    title: "Glamour in the Desert — Dubai",
    images: [img17, img18, img19, img20],
    gridItems: [
      { img: img17, caption: "Arlo Quinn" },
      { img: img18, caption: "Vera Kline" },
      { img: img19, caption: "Juno Vale" },
      { img: img20, caption: "Ember Dash" },
      { img: img21, caption: "Rylee Voss" },
      { img: img22, caption: "Harlow Nova" },
      { img: img23, caption: "Blake Lune" },
      { img: img24, caption: "Zephyr Kade" },
      { img: img25, caption: "Indigo Rae" },
      { img: img26, caption: "Kairo Jett" },
      { img: img27, caption: "Extra One" },
      { img: img30, caption: "Extra Two" },
    ],
  },
  {
    title: "Chic Couture Runway — Milan",
    images: [img31, img32, img33, img34],
    gridItems: [
      { img: img31, caption: "Arlo Quinn" },
      { img: img32, caption: "Vera Kline" },
      { img: img33, caption: "Juno Vale" },
      { img: img34, caption: "Ember Dash" },
      { img: img35, caption: "Rylee Voss" },
      { img: img36, caption: "Harlow Nova" },
      { img: img37, caption: "Blake Lune" },
      { img: img38, caption: "Zephyr Kade" },
      { img: img39, caption: "Indigo Rae" },
      { img: img40, caption: "Kairo Jett" },
      { img: img41, caption: "Extra One" },
      { img: img42, caption: "Extra Two" },
    ],
  },
  {
    title: "Style Showcase — London",
    images: [img42, img43, img44, img45],
    gridItems: [
      { img: img42, caption: "Yuki Star" },
      { img: img43, caption: "Ren Sora" },
      { img: img44, caption: "Mika Luna" },
      { img: img45, caption: "Aki Orion" },
      { img: img46, caption: "Hana Vega" },
      { img: img47, caption: "Rin Kai" },
      { img: img48, caption: "Sora Blaze" },
      { img: img49, caption: "Kyo Nova" },
      { img: img50, caption: "Extra One" },
      { img: img51, caption: "Extra Two" },
      { img: img52, caption: "Extra Three" },
      { img: img53, caption: "Extra Four" },
    ],
  },
  {
    title: "Celestial Runway — Tokyo",
    images: [img52, img53, img54, img55, img56], // Added img56 as the fifth image
    radius: 600,
    gridItems: [
      { img: img52, caption: "Min Jae" },
      { img: img53, caption: "Soo Jin" },
      { img: img54, caption: "Hyeon Woo" },
      { img: img55, caption: "Ara Moon" },
      { img: img56, caption: "Jisoo Vega" },
      { img: img57, caption: "Dae Sun" },
      { img: img58, caption: "Yuna Blaze" },
      { img: img59, caption: "Jin Kyung" },
      { img: img60, caption: "Extra One" },
      { img: img61, caption: "Extra Two" },
      { img: img62, caption: "Extra Three" },
      { img: img63, caption: "Extra Four" },
    ],
  },
  {
    title: "Neon Dreams — Seoul",
    images: [img64, img65, img66, img67],
    gridItems: [
      { img: img64, caption: "Eden Frost" },
      { img: img65, caption: "Milo Ash" },
      { img: img66, caption: "Nova Lane" },
      { img: img67, caption: "Sage Onyx" },
      { img: img68, caption: "River Lux" },
      { img: img69, caption: "Sky Vega" },
      { img: img70, caption: "Pax Wynn" },
      { img: img71, caption: "Lark Voss" },
      { img: img72, caption: "Echo Blaise" },
      { img: img63, caption: "Extra One" },
      { img: img64, caption: "Extra Two" },
      { img: img65, caption: "Extra Two" },
    ],
  },
];
